version: '3'

services:
  mysql:
    image: mysql:5.5
    container_name: agence
    volumes:
      - container-volume:/var/lib/mysql
      - ./banco_de_dados.sql:/docker-entrypoint-initdb.d/banco_de_dados.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cao
    ports:
      - "3306:3306"

volumes:
  container-volume:
